#!/bin/bash

# Download necessary packages for sentiment analysis development.
# This script assumes you have already created your virtual environment
# Run it from the directory where you created your virtual environment

# Stop on errors, print commands
set -Eeuo pipefail
set -x

# Activate virtual environment
source env/bin/activate

# Download packages
pip install scikit-learn
pip install matplotlib
pip install tensorflow
pip install keras