steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/eecs-441-musicsharingnetwork/backend', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/eecs-441-musicsharingnetwork/backend']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'backend', '--image', 'gcr.io/eecs-441-musicsharingnetwork/backend', '--region', 'us-central1', '--allow-unauthenticated', '--platform', 'managed']
images:
- gcr.io/eecs-441-musicsharingnetwork/backend